export const siteConfig = {
  name: "TiviMate",
  url: "https://tivimateplayer.us",
  primaryKeyword: "TiviMate IPTV Player",
  title: "IPTV UK – Premium IPTV Subscription UK | 20,000+ Channels & Free Trial",
  description:
    "Access IPTV UK with 20,000+ live channels, sports, movies and series. Free trial available, instant activation, guided setup and 24/7 support.",
  h1: "IPTV UK – Premium IPTV Subscription from £9.99 with Free 24-Hour Trial",
  keywords: [
    "TiviMate IPTV Player",
    "TiviMate IPTV",
    "IPTV for TiviMate",
    "TiviMate IPTV subscription",
    "IPTV for TiviMate app",
    "TiviMate IPTV service",
    "TiviMate player",
    "TiviMate IPTV app",
    "IPTV on TiviMate",
    "IPTV subscription for TiviMate",
    "TiviMate compatible IPTV",
    "IPTV for Firestick",
    "IPTV for Android TV",
    "TiviMate IPTV setup",
  ],
} as const;

/**
 * Final keyword ownership (avoid commercial cannibalization):
 * Home → TiviMate IPTV Player | Plans → TiviMate IPTV Subscription
 * Installation → TiviMate IPTV | Blog → TiviMate IPTV Blog | Contact → TiviMate IPTV Support
 */
export const pageKeywordOwnership = {
  home: "TiviMate IPTV Player",
  plans: "TiviMate IPTV Subscription",
  installation: "TiviMate IPTV",
  blog: "TiviMate IPTV Blog",
  contact: "TiviMate IPTV Support",
} as const;

export const routes = {
  home: "/",
  trial: "/contact-us",
  plans: "/iptv-plans",
  installation: "/installation-guide",
  blog: "/blog",
  contact: "/contact-us",
} as const;

/** Digits only, country code included (example: 447700900123). */
const whatsappNumber = "447482794475";

const whatsappMessage = encodeURIComponent(
  "Hi, I need help with my TiviMate IPTV subscription.",
);

export const supportConfig = {
  email: "support@tivimateplayer.us",
  whatsapp: "+44 7482 794475",
  whatsappUrl: `https://wa.me/${whatsappNumber}?text=${whatsappMessage}`,
  downloaderCode: "",
} as const;

/** Optimized brand assets served from /public (generated by scripts/generate-brand-icons.mjs). */
export const brandAssets = {
  logo: "/logo-main.png",
  logoMark: "/logo-mark.png",
  logo512: "/logo-512.png",
  ogImage: "/og-image.png",
  favicon48: "/favicon-48.png",
  appleTouchIcon: "/apple-touch-icon.png",
  manifest: "/site.webmanifest",
} as const;

export const navLinks = [
  { href: routes.home, label: "Home" },
  { href: routes.plans, label: "IPTV Plans" },
  { href: routes.installation, label: "Setup Guide" },
  { href: routes.blog, label: "Blog" },
  { href: routes.contact, label: "Contact" },
] as const;

export const footerQuickLinks = [
  { href: routes.plans, label: "View IPTV Plans" },
  { href: routes.installation, label: "How to Set Up TiviMate" },
  { href: "/#faq", label: "FAQ" },
] as const;

export const footerLegalLinks = [
  { href: routes.contact, label: "Contact Support" },
] as const;
